//static const char col_borderbar[]  = "#1a1b26"; // inner border

static const char red[]		= "#f7768e"; //This keyword, HTML elements, Regex group symbol, CSS units, Terminal Red
static const char orange[]      = "#ff9e64"; //#Number and Boolean constants, Language support constants
static const char yellow[]      = "#e0af68"; //Function parameters, Regex character sets, Terminal Yellow
static const char green[]       = "#9ece6a"; //#Strings, CSS class names
static const char tgreen[]      = "#73daca"; //Object literal keys, Markdown links, Terminal Green	
static const char whitegreen[]  = "#b4f9f8"; //Regex literal strings
static const char cyan[]        = "#2ac3de"; //Language support functions, CSS HTML elements
static const char lblue[]       = "#7dcfff"; //Object properties, Regex quantifiers and flags, Markdown headings, Terminal Cyan, Markdown code, Import/export keywords
static const char blue[]        = "#7aa2f7";  // focused window border
static const char purple[]      = "#bb9af7"; //Control Keywords, Storage Types, Regex symbols and operators, HTML Attributes, Terminal Magenta
static const char twhite[]	= "#c0caf5"; //Variables, Class names, Terminal White
static const char white[]	= "#a9b1d6"; //Editor Foreground
static const char lgrey[]	= "#9aa5ce"; //Markdown Text, HTML Text
static const char baje[]	= "#cfc9c2"; //Parameters inside functions (semantic highlighting only)
static const char grey[]	= "#565f89"; //Comments
static const char tblack[]	= "#414868"; //Terminal Black
static const char black1[] 	= "#24283b"; //Editor Background (Storm)
static const char black2[]	= "#1a1b26"; //Editro Background (Night)
