#!/bin/dash

# colors

black=#1a1b26
black2=#24283b
terminalb=#0f0f14
green=#9ece6a
white=#a9b1d6
grey=#24283b
blue=#7aa2f7
red=#f7768e
darkblue=$blue
yellow=#e0af68
orange=#ff9e64
lorange=#965027
lyellow=#8f5e15
lred=#8c4351
lgreen=#485e30