#!/bin/dash

# colors

black=#1a1b26
black2=#24283b
terminalb=#0f0f14
green=#9ece6a
white=#a9b1d6
grey=#24283b
blue=#7aa2f7
red=#f7768e
darkblue=$blue
yellow=#e0af68
orange=#ff9e64
lgorange=#d65d0e #lighter 1
dgorange=#af3a03 #darker 2 
gyellow=#d79921
gred=#9d0006
dggreen=#98971a
lggreen=#b8bb26 #lighter 2
gaqua=#8ec07c